google and mail auth bloc
hireflutter-dev/start-flutter pull request #23
Opened 2022-03-16 04:31 UTC by vaishnavi-2307

2022-04-13 09:07 UTC, japatel225 commented on lib/src/app/feature/authentication/presentation/login_screen.dart
> +                                          onTap: () async {
I see `async` is not added in this PR and is not related to the task of this PR, but can we remove it if not required? Or should we do such unrelated "clean-up" changes (this one and others if any) in separate PR ideally? Let me know your thoughts.

2022-04-13 09:18 UTC, japatel225 commented on lib/src/app/feature/authentication/presentation/login_screen.dart
> +                child:SizedBox.shrink());
same comment regarding code auto-format.

2022-04-25 08:27 UTC, japatel225 commented on android/app/src/google-services.json
> +{
Can you move this file to path "android/app/google-services.json" or add it to .gitignore? So it won't be a part of the open-source repo. Users of the repo can add their own google-services.json file.

2022-04-25 08:30 UTC, japatel225 commented on lib/src/app/feature/email_authentication/presentation/register.dart
> +  String? isEmailValid(String? value) {
Can you move this and `isPasswordValid` methods to after the build method?

2022-04-25 08:30 UTC, japatel225 requested changes
Please also resolve the conflicts.

2022-10-10 04:10 UTC, Abhishek01039 approved these changes
LGTM!

2022-10-10 04:10 UTC, merged