phone login problem fix
hireflutter-dev/start-flutter pull request #26
Opened 2022-10-07 03:52 UTC by a4adityaa

2022-10-07 04:18 UTC, Abhishek01039 requested changes

2022-10-07 04:18 UTC, Abhishek01039 commented on lib/src/app/feature/authentication/presentation/viewmodel/auth_view_model.dart
> +      verified = true;
No need to create a variable. just return true and false

2022-10-07 04:18 UTC, Abhishek01039 commented on lib/src/app/feature/authentication/presentation/viewmodel/auth_view_model.dart
> +          await confirmationResult?.confirm('$smsCode');
Please revert this changes, it's already same as pervious version

2022-10-10 04:02 UTC, a4adityaa commented
https://user-images.githubusercontent.com/114215653/194797682-1a2ade2e-4b56-4d55-b747-b45ff684f5aa.mp4

2022-10-10 04:08 UTC, Abhishek01039 approved these changes
LGTM!

2022-10-10 04:08 UTC, merged